# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

"""Per-container dnsmasq lifecycle: config generation, launch, and cleanup.

dnsmasq runs inside the container's network namespace (via ``nsenter``),
listens on ``127.0.0.1:53``, and uses ``--nftset`` to auto-populate nft
allow sets on every DNS resolution.  This handles IP rotation that
static pre-start resolution cannot.

This module is the single owner of dnsmasq config format and CLI args.
"""

from __future__ import annotations

import os
import re
import signal
from pathlib import Path
from typing import TYPE_CHECKING

from . import state
from .nft_constants import DNSMASQ_BIND, NFT_TABLE_NAME

if TYPE_CHECKING:
    from .run import CommandRunner

# ── Constants ────────────────────────────────────────────

_NFTSET_FEATURE = "nftset"
_NFTSET_ABSENT = "no-nftset"

# Strict domain label validation (RFC 1035 + wildcards).
# Allows: a-z, 0-9, hyphens, dots, leading wildcard (*.).
_DOMAIN_RE = re.compile(r"^(\*\.)?([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?\.)*[a-zA-Z]{2,}$")


# ── Config generation ────────────────────────────────────


def _validate_domain(domain: str) -> str:
    """Validate a domain name against injection.

    Raises ValueError on invalid input.
    """
    d = domain.strip().lower()
    if not d:
        raise ValueError("Empty domain name")
    if not _DOMAIN_RE.fullmatch(d):
        raise ValueError(f"Invalid domain name: {d!r}")
    return d


def nftset_entry(domain: str) -> str:
    """Generate a dnsmasq ``nftset`` config line for a domain.

    Maps A records to the IPv4 allow set and AAAA records to the IPv6
    allow set.  dnsmasq automatically matches the domain and all its
    subdomains.

    Example::

        nftset=/github.com/4#inet#terok_shield#allow_v4,6#inet#terok_shield#allow_v6
    """
    domain = _validate_domain(domain)
    # Strip leading wildcard — dnsmasq nftset inherently matches subdomains.
    if domain.startswith("*."):
        domain = domain[2:]
    return f"nftset=/{domain}/4#inet#{NFT_TABLE_NAME}#allow_v4,6#inet#{NFT_TABLE_NAME}#allow_v6"


def generate_config(
    upstream_dns: str,
    domains: list[str],
    pid_path: Path,
) -> str:
    """Generate a complete dnsmasq configuration.

    Args:
        upstream_dns: Upstream DNS forwarder (pasta or slirp4netns address).
        domains: Domain names for ``--nftset`` auto-population.
        pid_path: Path for the dnsmasq PID file.
    """
    lines = [
        f"# Generated by terok-shield (pid {os.getpid()})",
        f"listen-address={DNSMASQ_BIND}",
        "port=53",
        "bind-interfaces",
        "no-resolv",
        "no-hosts",
        f"server={upstream_dns}",
        f"pid-file={pid_path}",
    ]
    for domain in domains:
        try:
            lines.append(nftset_entry(domain))
        except ValueError:
            continue  # skip invalid domains silently
    return "\n".join(lines) + "\n"


# ── HAVE_NFTSET detection ────────────────────────────────


def has_nftset(runner: CommandRunner) -> bool:
    """Return True if the installed dnsmasq supports ``--nftset``.

    Checks ``dnsmasq --version`` compile options for ``nftset`` (present)
    vs ``no-nftset`` (absent).  Returns False if dnsmasq is not installed.
    """
    output = runner.dnsmasq_version()
    if not output:
        return False
    return _NFTSET_FEATURE in output and _NFTSET_ABSENT not in output


# ── Lifecycle ────────────────────────────────────────────


def launch(
    runner: CommandRunner,
    pid: str,
    state_dir: Path,
    upstream_dns: str,
    domains: list[str],
) -> None:
    """Generate config and launch dnsmasq in the container's network namespace.

    dnsmasq daemonizes and writes its PID to the state directory.

    Args:
        runner: Command runner for subprocess calls.
        pid: Container PID (for nsenter).
        state_dir: Per-container state directory.
        upstream_dns: Upstream DNS forwarder address.
        domains: Domain names for nftset auto-population.

    Raises:
        RuntimeError: If dnsmasq fails to start or PID file is not written.
    """
    conf_path = state.dnsmasq_conf_path(state_dir)
    pid_path = state.dnsmasq_pid_path(state_dir)

    config = generate_config(upstream_dns, domains, pid_path)
    conf_path.write_text(config)

    # Launch dnsmasq inside the container's network namespace.
    # --keep-in-foreground is NOT used: dnsmasq daemonizes and writes PID.
    cmd = [
        "nsenter",
        "-t",
        pid,
        "-n",
        "--",
        "dnsmasq",
        f"--conf-file={conf_path}",
    ]
    runner.run(cmd, check=True)

    if not pid_path.is_file():
        raise RuntimeError(
            f"dnsmasq started but PID file not written at {pid_path}. "
            "The container's DNS may not be functional."
        )


def kill(state_dir: Path) -> None:
    """Kill dnsmasq for a container (best-effort cleanup).

    Reads the PID from the state directory and sends SIGTERM.
    Silently ignores missing PID files, stale PIDs, and permission errors.
    This is defense-in-depth — the network namespace teardown at container
    exit normally kills dnsmasq first.
    """
    pid_path = state.dnsmasq_pid_path(state_dir)
    try:
        pid_str = pid_path.read_text().strip()
        pid_int = int(pid_str)
    except (OSError, ValueError):
        return
    try:
        os.kill(pid_int, signal.SIGTERM)
    except (ProcessLookupError, PermissionError):
        pass


def reload(
    runner: CommandRunner,
    container_pid: str,
    state_dir: Path,
    upstream_dns: str,
    domains: list[str],
) -> None:
    """Regenerate dnsmasq config, kill the old instance, and relaunch.

    Used after ``shield allow/deny`` changes the domain list, or by
    ``shield reload`` for manual recovery.

    Args:
        runner: Command runner for subprocess calls.
        container_pid: Container PID (for nsenter into its network namespace).
        state_dir: Per-container state directory.
        upstream_dns: Upstream DNS forwarder address.
        domains: Updated domain names for nftset auto-population.

    Raises:
        RuntimeError: If dnsmasq fails to restart.
    """
    kill(state_dir)
    launch(runner, container_pid, state_dir, upstream_dns, domains)


def add_domain(state_dir: Path, domain: str) -> bool:
    """Append a domain to the profile.domains file.

    Returns True if the domain was added, False if already present.
    """
    domain = _validate_domain(domain)
    domains_path = state.profile_domains_path(state_dir)
    existing = _read_domains(domains_path)
    if domain in existing:
        return False
    with domains_path.open("a") as f:
        f.write(f"{domain}\n")
    return True


def remove_domain(state_dir: Path, domain: str) -> bool:
    """Remove a domain from the profile.domains file.

    Returns True if the domain was removed, False if not found.
    """
    domain = _validate_domain(domain)
    domains_path = state.profile_domains_path(state_dir)
    existing = _read_domains(domains_path)
    if domain not in existing:
        return False
    existing.remove(domain)
    domains_path.write_text("\n".join(existing) + "\n" if existing else "")
    return True


def _read_domains(domains_path: Path) -> list[str]:
    """Read domain names from a domains file."""
    if not domains_path.is_file():
        return []
    return [line.strip() for line in domains_path.read_text().splitlines() if line.strip()]


def write_resolv_conf(pid: str, nameserver: str = DNSMASQ_BIND) -> None:
    """Overwrite the container's resolv.conf to point to dnsmasq.

    Safety measure backing up the ``--dns`` podman flag.  Writes directly
    to ``/proc/{pid}/root/etc/resolv.conf`` from the host side.
    """
    resolv_path = Path(f"/proc/{pid}/root/etc/resolv.conf")
    resolv_path.write_text(f"nameserver {nameserver}\n")
